# Generated by Django 4.0.4 on 2022-05-13 01:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter your name here', max_length=255)),
                ('email', models.EmailField(default='@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91', max_length=15)),
                ('city', models.CharField(default='Mumabi', max_length=255)),
                ('country', models.CharField(default='India', max_length=255)),
                ('message', models.TextField(default='Start writing your message here...')),
                ('time_of_message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.FileField(default='media/no_img.png', upload_to='BlogImages')),
                ('links', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('references', models.CharField(max_length=255)),
                ('code', ckeditor.fields.RichTextField()),
                ('blog_written_by', models.CharField(default='Mubashir Mustafa', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Check for publish your post online')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
